version: '2'
services:
 mysql-database:
  image: mysql:5.7
  restart: always
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_PASSWORD=root
   - MYSQL_DATABASE=cmsdb
   - MYSQL_ALLOW_EMPTY_PASSWORD=yes
